### ISSUE TITLE
和RefinedNowPlaying的冲突

### ISSUE THREAD

**Issue by rainyorange** [mo-jinran/MoTheme#1]
![image](https://user-images.githubusercontent.com/36807368/207553703-a6988836-b972-4350-a296-102ccf02edd4.png)
音量条好了 红心还是那样（）

**Comment by mo-jinran** [comment]
好怪，不是很会修（毕竟这俩插件单独用都是好的

**Comment by rainyorange** [comment]
（挠头）

**Comment by mo-jinran** [comment]
这个我肯定会想办法修的，毕竟RefinedNowPlaying我也用的（（

**Comment by rainyorange** [comment]
![image](https://user-images.githubusercontent.com/36807368/207554967-487b0e48-21bb-4548-8644-cdaab1631b1b.png)
禁用Motheme后就没红心问题了
是不是改了红心的啥东西（）

**Comment by mo-jinran** [comment]
找到了，这行样式的问题
https://github.com/mo-jinran/MoTheme/blob/main/theme.css#L172

**Comment by rainyorange** [comment]
好耶

**Comment by mo-jinran** [comment]
已修复
