### ISSUE TITLE
希望能移除默认背景图

### ISSUE THREAD

**Issue by YiQuSi** [mo-jinran/MoTheme#10]
在MoTheme版本更新之后，默认加载一张天空背景图，对于喜欢原版的纯色的用户不太友好。
要修改背景图，只能依赖BGEnhanced插件，而此插件似乎尚未完善。
这样的默认背景图影响了界面的易读性。

综上所述，希望能移除默认背景图。

**Comment by xchangfu** [comment]
同样希望移除默认背景图，每次打开网易云音乐都会先加载默认背景图，然后加载自定义的背景图，体验有点割裂

**Comment by cale044** [comment]
支持
