### ISSUE TITLE
[BUG] 与BG Enhanced一起使用时，评论区翻页后网易云页面错位

### ISSUE THREAD

**Issue by lgc2333** [mo-jinran/MoTheme#15]
https://github.com/solstice23/refined-now-playing-netease/issues/142

**Comment by xycld** [comment]
我这没这个问题，你更新下版本试试

**Comment by lgc2333** [comment]
> 我这没这个问题，你更新下版本试试

是插件商城的最新版啊

**Comment by xycld** [comment]
可否附图

**Comment by lgc2333** [comment]
全部插件
![image](https://user-images.githubusercontent.com/59048777/234590004-1e78a7e4-26e4-438d-ad63-dfcd95019ccf.png)

![image](https://user-images.githubusercontent.com/59048777/234590093-1c28bbbf-5713-4c15-8210-48aef0e87ad3.png)

**Comment by xycld** [comment]
我指的是问题发生的时候的图片

**Comment by lgc2333** [comment]
> [solstice23/refined-now-playing-netease#142](https://github.com/solstice23/refined-now-playing-netease/issues/142)

**Comment by xycld** [comment]
我装的插件比你还多，但是仍然无法复现，我感觉是屏幕分辨率的问题，你是2k以上屏幕吗，我看着有点像

**Comment by lgc2333** [comment]
> 

1080p 100%缩放

**Comment by xycld** [comment]
确定了，BGE的锅，换地方吧提issue吧
你可以先删除BGE，确定bug不再存在的话，可以close了

**Comment by xycld** [comment]
等会，我再确认一下这三个插件到底是谁和谁不兼容（

**Comment by xycld** [comment]
是RefinedNowPlaying和BGEnhanced不兼容，我建议你发两个issue

**Comment by lgc2333** [comment]
> 是RefinedNowPlaying和BGEnhanced不兼容，我建议你发两个issue

好的
