### ISSUE TITLE
背景图在BetterNCM 1.0中重启失效

### ISSUE THREAD

**Issue by TTsdzb** [mo-jinran/MoTheme#2]
- 复现方法
    1. 安装 BetterNCM 1.0 和本主题，使用本主题自带功能设置一个图片背景，可以正常设置。
    2. 重启网易云，发现刚刚设置的背景无法加载。

- 原因
    现在的背景图直接记录 URL，这在之前的版本中没什么问题。但更新到 1.0 版本后其 HTTP 服务改成了随机端口，导致软件重启后记录的地址失效。

**Comment by mo-jinran** [comment]
StylesheetLoader插件的BUG，这个插件是BetterrNCM的主题依赖，没有开源仓库所以我没办法修，请通知 @MicroCBer

**Comment by TTsdzb** [comment]
[BetterNCM中的 issue](https://github.com/MicroCBer/BetterNCM/issues/166)
