### ISSUE TITLE
播放列表会闪现

### ISSUE THREAD

**Issue by Kylar6** [mo-jinran/MoTheme#3]
![image](https://user-images.githubusercontent.com/44493297/210551440-8a922c1d-d0d1-4ead-b2d1-9468c5ec0ac6.png)
bof

播放列表会闪现

**Comment by Kylar6** [comment]
https://user-images.githubusercontent.com/44493297/210555010-012bb75e-76ba-4f3c-aced-3ad777902f5e.mp4

**Comment by mo-jinran** [comment]
播放列表、私信、个人信息打开后会消失，不装任何插件也可以复现（这是玄学问题），而且很难遇到这种情况不好修

**Comment by mo-jinran** [comment]
目前只有尝试重启网易云或更新到最新版解决
