### ISSUE TITLE
使用MoTheme网易云弹窗闪退

### ISSUE THREAD

**Issue by longlongyo** [mo-jinran/MoTheme#6]
https://user-images.githubusercontent.com/85000220/211186902-db3bdd21-1de8-471b-a01f-31db263ea8ce.mp4

**Comment by wy164519317** [comment]
该说不说，背景能不能分享下

**Comment by longlongyo** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mo-jinran/MoTheme"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月12日(星期四) 晚上7:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mo-jinran/MoTheme] 使用MoTheme网易云弹窗闪退 (Issue #6)





 
该说不说，背景能不能分享下
