### ISSUE TITLE
概率卡顿

### ISSUE THREAD

**Issue by pop-tianlang** [mo-jinran/MoTheme#7]
使用mo theme时加滚轮调节音量时，会有概率卡顿

**Comment by mo-jinran** [comment]
操作增强插件的问题

**Comment by mo-jinran** [comment]
它这个插件还没有修bug

**Comment by pop-tianlang** [comment]
作者大大什么时候修复那个背景的问题呀

**Comment by mo-jinran** [comment]
背景也不是我插件问题，StylesheetLoader插件问题。橘子想要废弃此插件，并且重构BGEnhanced插件提供主题背景功能，到时候MoTheme会使用BGEnhanced设置背景

**Comment by mo-jinran** [comment]
BGEnhanced插件已经正在重构了，等着以后我适配吧
