### ISSUE TITLE
[Bug]设置自定义背景后重启网易云会丢失

### ISSUE THREAD

**Issue by Xionghaizi001** [mo-jinran/MoTheme#8]
Bug描述：设置自定义背景后，下次打开网易云，背景会丢失，但设置页面仍显示使用了自定义背景且相应目录能找到对应文件
~~有可能是BetterNCM更新到1.0的锅？~~

**Comment by lingMori** [comment]
和BGEnhanced插件一起使用就行了（如果会的话，自己改改js代码也不是能用(╹ڡ╹ )）
